# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 07:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_page', '0002_auto_20160914_0631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentpagecarouselitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='contentpagecarouselitem',
            name='page',
        ),
        migrations.AlterModelOptions(
            name='contentpage',
            options={'verbose_name': 'Content page'},
        ),
        migrations.DeleteModel(
            name='ContentPageCarouselItem',
        ),
    ]
