# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 07:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content_page', '0005_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageNameField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
        ),
        migrations.AlterModelOptions(
            name='contentpage',
            options={},
        ),
        migrations.AddField(
            model_name='homepagenamefield',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousel_items', to='content_page.ContentPage'),
        ),
    ]
