# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 07:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0013_make_rendition_upload_callable'),
        ('content_page', '0006_auto_20160914_0749'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPageCarouselItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('embed_link', models.URLField(verbose_name='Embed URL')),
                ('caption', models.CharField(max_length=250)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousel_items', to='content_page.ContentPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='homepagenamefield',
            name='page',
        ),
        migrations.DeleteModel(
            name='HomePageNameField',
        ),
    ]
