# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 08:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content_page', '0007_auto_20160914_0751'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='contentpagecarouselitem',
            name='id',
        ),
        migrations.AddField(
            model_name='contentpagecarouselitem',
            name='linkfields_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content_page.LinkFields'),
            preserve_default=False,
        ),
    ]
