# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_page', '0011_auto_20160914_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpagecarouselitem',
            name='external_link',
            field=models.URLField(blank=True, verbose_name='External url'),
        ),
    ]
