# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 12:14
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content_page', '0014_auto_20160914_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('pullquote', wagtail.wagtailcore.blocks.StructBlock((('quote', wagtail.wagtailcore.blocks.TextBlock('Quote title')), ('attribution', wagtail.wagtailcore.blocks.CharBlock())))),), blank=True, null=True),
        ),
    ]
