# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 16:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20160917_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageb',
            old_name='image',
            new_name='imagee',
        ),
    ]
