# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='map_lat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contactform',
            name='map_long',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contactform',
            name='map_zoom_level',
            field=models.CharField(default=14, max_length=3),
        ),
    ]
