# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0002_auto_20160918_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='map_zoom_level',
            field=models.CharField(blank=True, default=14, max_length=3, null=True),
        ),
    ]
