# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0003_auto_20160920_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='show_map',
            field=models.BooleanField(default=True),
        ),
    ]
