# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0004_contactform_show_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='map_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
