# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20160916_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookpage',
            name='template_string',
            field=models.CharField(choices=[('One', 'book/one.html'), ('Two', 'book/two.html')], default='One', max_length=250),
        ),
    ]
