# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_bookpage_template_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookpage',
            name='template_string',
            field=models.CharField(choices=[('book/book_page.html', 'Book Page'), ('book/one.html', 'One'), ('book/two.html', 'Two')], default='book/one.html', max_length=250),
        ),
    ]
