# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20160917_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookpage',
            name='template_string',
            field=models.CharField(choices=[('book/book_page.html', 'Book Page Template'), ('book/one.html', 'Design One'), ('book/two.html', 'Design Two')], default='book/one.html', max_length=250),
        ),
    ]
